spring:
  datasource:
    url: jdbc:mysql://localhost:3308/sean?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true #@Result来指明结果映射 精简版配置

server:
  port: 8088
  max-http-header-size: 4048576

#logging:
#  level:
#    root: debug

devtools:
  restart:
    enabled: true  #设置开启热部署

freemarker:
  cache: false    #页面不加载缓存，修改即时生效
